### PR TITLE
Linear Sum Agreement Algorithm

### PR DESCRIPTION
**Pull request by daniel-klein**
Experimenting with pair formation via linear sum agreement (LSA), as in EmbeddingNet.

Resulting pars are a bit different, LSA is on the right.
image

### CODE REVIEW

**Comment by daniel-klein** [comment]
Note, LSA will create at most one partner per person per step, unlike the previous algorithm, so would be good to check concurrency.

**Comment by daniel-klein** [comment]
image

**Comment by daniel-klein** [comment]
Main takes 10.37 s and this branch is 19.59 s, so about 2x slower with LSA.

**Comment by daniel-klein** [comment]
In the lifetime partners plot above, I'm surprise to see LSA making so many very high results. Not sure what's going on there!

**Comment by robynstuart** [comment]
Closing this for now, can re-open once repo is up to date with latest starsim

**Pull request closed without merging**
